### ISSUE TITLE
transfer_amount.sh: line 67: use:: command not found

### ISSUE THREAD

**Issue by AlexeySpiridonov** [FreeTON-Network/custler.uninode#2]
Wallet Code: /root/custler.uninode/ton-labs-contracts/solidity/safemultisig/SafeMultisigWallet.tvc
ABI for wallet: /root/custler.uninode/ton-labs-contracts/solidity/safemultisig/SafeMultisigWallet.abi.json
./transfer_amount.sh: line 67: use:: command not found
error: The following required arguments were not provided:
    <AMOUNT>

**Comment by AlexeySpiridonov** [comment]
./transfer_amount.sh 20000
################################### Send tokens script ########################################
./transfer_amount.sh: line 30: use:: command not found

**Comment by Custler** [comment]
Thanks! 
Bugfix commited!

USE:
./transfer_amount.sh <SRC> <DST> <AMOUNT> [new]"
where [new] - for transfer to not activated account (for creation)"
