### ISSUE TITLE
лег телеграмм бот

### ISSUE THREAD

**Issue by AlexeySpiridonov** [FreeTON-Network/custler.uninode#4]
не шлет ничего

**Comment by AlexeySpiridonov** [comment]
./tg_check_node_sync_status.sh 
jq: error (at <stdin>:1): Cannot index string with string "timediff"
parse error: Expected string key before ':' at line 1, column 26
rustnet Time: 2021-07-30 21:04:47 CEST TimeDiff:

**Comment by Custler** [comment]
fixed
